/**
 * useResults Hook
 * Manages results display, sharing, and saving
 */

import { useState, useCallback } from 'react';
import * as Sharing from 'expo-sharing';
import { File, Paths } from 'expo-file-system';
import * as Clipboard from 'expo-clipboard';
import { Platform } from 'react-native';

export function useResults() {
    const [sharing, setSharing] = useState(false);
    const [saving, setSaving] = useState(false);

    /**
     * Copies text to clipboard
     */
    const copyToClipboard = useCallback(async (text) => {
        try {
            await Clipboard.setString(text);
            return true;
        } catch (error) {
            return false;
        }
    }, []);

    /**
     * Shares text using native sharing
     */
    const shareText = useCallback(async (text, title = 'Arabic Video Translator Results') => {
        try {
            setSharing(true);
            if (Platform.OS === 'web') {
                if (navigator.share) {
                    await navigator.share({ title, text });
                    setSharing(false);
                    return true;
                }
                const blob = new Blob([text], { type: 'text/plain' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'translation_results.txt';
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
                setSharing(false);
                return true;
            } else {
                const file = new File(Paths.document, 'translation_results.txt');
                file.write(text);
                const isAvailable = await Sharing.isAvailableAsync();
                if (!isAvailable) {
                    throw new Error('Sharing is not available on this device');
                }
                await Sharing.shareAsync(file.uri, {
                    mimeType: 'text/plain',
                    dialogTitle: title,
                });
                file.delete();
                setSharing(false);
                return true;
            }
        } catch (error) {
            // Silent fail
            setSharing(false);
            return false;
        }
    }, []);

    /**
     * Saves results to device storage
     */
    const saveResults = useCallback(async (results, filename = 'translation_results.txt') => {
        try {
            setSaving(true);
            const content = formatResultsForSave(results);
            if (Platform.OS === 'web') {
                const blob = new Blob([content], { type: 'text/plain' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = filename;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
                setSaving(false);
                return null;
            } else {
                const file = new File(Paths.document, filename);
                file.write(content);
                setSaving(false);
                return file.uri;
            }
        } catch (error) {
            setSaving(false);
            return null;
        }
    }, []);

    /**
     * Formats results for saving
     */
    const formatResultsForSave = useCallback((results) => {
        let content = '=== Arabic Video Translator Results ===\n\n';

        if (results.arabicTranscript) {
            content += '--- Arabic Transcript ---\n';
            content += results.arabicTranscript + '\n\n';
        }

        const translation = results.translatedText || results.dutchTranslation;
        if (translation) {
            content += '--- Translation ---\n';
            content += translation + '\n\n';
        }

        if (results.duaResults) {
            content += '--- Dua Extraction ---\n';
            content += results.duaResults + '\n\n';
        }

        content += 'Generated by Arabic Video Translator\n';
        return content;
    }, []);

    return {
        sharing,
        saving,
        copyToClipboard,
        shareText,
        saveResults,
        formatResultsForSave,
    };
}
